My First R Program

1. PRINT

In [ ]:
print ("Hello World")

Hello World

2. CLASS

In [ ]:
myString <- "Hello World"
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class (myString)
class (num)
class (floatingNum)
class (isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. OPERATION

In [ ]:
x <- 5
y <- 3

add <- x + y
sub <- x - y
multiply <- x * y
divide <- x / y

print (paste0("Add: ", add))
print (paste0("Subtract: ", sub))
print (paste0("Multiply: ", multiply))
print (paste0 ("Divide: ", divide))

[1] "Add: 8"
[1] "Subtract: 2"
[1] "Multiply: 15"
[1] "Divide: 1.66666666666667"

4. USER INPUT

In [ ]:
name = readline ("Enter Name: ")
print(paste("Name: ", name))

Enter Name: Jill
[1] "Name:  Jill"

5. IF ELSE

In [ ]:
grade <- 72

if (grade < 75){
  print ("Failed")
}else{
  print ("Passed")
}

[1] "Failed"

6. LOOP

In [ ]:
for ( i in 1:5){
  print (i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. FUNCTION

In [ ]:
addNumber <- function (a,b){
  return (a + b)
}

addNumber (5, 3)

[1] 8

8. VECTORS

In [ ]:
grades <- c(90, 85, 97, 98, 99)

grades

cat("MEAN: ", mean(grades))
cat("\nMAX: ", max(grades))
cat("\nMIN: ",min(grades))
cat("\nSUM: ", sum(grades))
cat("\nLENGTH: ", length(grades))

[1] 90 85 97 98 99

MEAN:  93.8
MAX:  99
MIN:  85
SUM:  469
LENGTH:  5

9. MATRICES

In [ ]:
A <- matrix(c(1,2,3,4,5,6),nrow = 2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. LISTS

In [ ]:
student <- list(
  Name = "John",
  Age = 20,
  GPA = 1.5
)

student

$Name
[1] "John"

$Age
[1] 20

$GPA
[1] 1.5

11. DATA FRAME

In [ ]:
student <- data.frame(
  Name = c("John", "Mary","Anna"),
  Age = c(20, 21, 19),
  GPA = c(1,1,1)
)
student
write.csv(student, "student.csv")

  Name Age GPA
1 John 20  1
2 Mary 21  1
3 Anna 19  1

12. READ CSV

In [ ]:
data <- read.csv("student.csv")

head(data)

summary (data)

  X Name Age GPA
1 1 John 20  1
2 2 Mary 21  1
3 3 Anna 19  1

       X              Name        Age            GPA
 Min.   :1.0   Length   :3   Min.   :19.0   Min.   :1
 1st Qu.:1.5   N.unique :3   1st Qu.:19.5   1st Qu.:1
 Median :2.0   N.blank  :0   Median :20.0   Median :1
 Mean   :2.0   Min.nchar:4   Mean   :20.0   Mean   :1
 3rd Qu.:2.5   Max.nchar:4   3rd Qu.:20.5   3rd Qu.:1
 Max.   :3.0                 Max.   :21.0   Max.   :1